* Documentation
I use Emacs often to explore documentation in both ~man~ and ~info~ formats. I customise the experience a little, and also make use of a couple of other tools to explore documentation in Emacs.
** Man customisation
I prefer to read man pages without line numbers, and sometimes read them on narrow screens (e.g. a phone), so wrapping lines properly is important.
#+begin_src elisp
(setq Man-notify-method 'pushy)
(defun ak/man-mode-hook ()
  (visual-line-mode)
  (adaptive-wrap-prefix-mode)
  (display-line-numbers-mode -1))
(add-hook 'Man-mode-hook #'ak/man-mode-hook)
#+end_src
*** Keybinding for man-mode
#+begin_src elisp :results none
(global-set-key (kbd "C-x A m") #'man)
#+end_src
*** Use gsed on mac os
=sed= doesn't seem to work well for me on Mac OS, whereas GNU =sed= behaves as expected. Install it with =brew install gsed=.
#+begin_src elisp :results none
(if (string= system-type "darwin")
    (setq Man-sed-command "gsed"))
#+end_src
** Info customisation
Similar to man pages, I prefer to read info pages without line numbers, and sometimes read them on a phone.
#+begin_src elisp :results none
(use-package adaptive-wrap :ensure t)
(defun ak/info-mode-hook ()
  (visual-line-mode)
  (adaptive-wrap-prefix-mode)
  (display-line-numbers-mode -1))
(add-hook 'Info-mode-hook #'ak/info-mode-hook)
#+end_src
** Emacs reader for PDFs
#+begin_src elisp :results none
(setq package-vc-allow-build-commands t)
(use-package reader
    :vc (:url "https://codeberg.org/divyaranjan/emacs-reader"
  	    :make "all"))
(defun ak/reader-mode-hook ()
  (display-line-numbers-mode -1)
  (reader-dark-mode)) ; open pdfs in dark mode by default
(add-hook 'reader-mode-hook #'ak/reader-mode-hook)
#+end_src
** Terraform docs
This is a handy package which downloads documentation for Terraform providers, and makes them browsable in Emacs.
#+begin_src elisp :results none
(use-package terraform-doc :ensure t)
#+end_src
** Devdocs
The =devdocs= package allows [[ https://devdocs.io][devdocs]] documentation to be browsed from within Emacs with ease:
#+begin_src elisp :results none
(use-package devdocs :ensure t)
(global-set-key (kbd "C-x A d i") #'devdocs-install)
(global-set-key (kbd "C-x A d d") #'devdocs-lookup)
#+end_src
** RFC mode
I often read RFCs in Emacs, since they are a great primary source of documentation:
#+begin_src elisp :results none
(use-package rfc-mode :ensure t)
(defun ak/rfc-mode-hook ()
  (visual-line-mode)
  (adaptive-wrap-prefix-mode)
  (display-line-numbers-mode -1))
(add-hook 'rfc-mode-hook #'ak/rfc-mode-hook)
#+end_src
** Noman
I've written a package for browsing command-line documentation, which I often use. It's on MELPA, but I prefer to load it locally in case I'm doing some work on it.
#+begin_src elisp :results none
(use-package noman
  :load-path "~/repos/andykuszyk/noman.el"
  :custom
  (noman-reuse-buffers nil))
(add-to-list 'display-buffer-alist '(".*noman.*" display-buffer-same-window))
(global-set-key (kbd "C-x A n") #'noman)
#+end_src
