(when (string= system-type "darwin")
  (org-babel-load-file (concat user-emacs-directory "darwin.org")))
(when (string= system-type "gnu/linux")
  (org-babel-load-file (concat user-emacs-directory "linux.org")))
(org-babel-load-file (concat user-emacs-directory "emacs.org"))
(org-babel-load-file (concat user-emacs-directory "org.org"))
(org-babel-load-file (concat user-emacs-directory "languages.org"))
(add-to-list 'load-path "~/.emacs.d/lisp")
(require 'jira)
(require 'github)
(if (file-exists-p "~/.emacs.d/lisp/custom-init.el")
    (load-file "~/.emacs.d/lisp/custom-init.el"))
