* Packages and configuration for writing
** Olivetti
Olivetti mode balances margins so that the text you are writing is centered in the window.
#+begin_src elisp :results none
(use-package olivetti :ensure t)
#+end_src
** Install fonts
I use the Computer Modern font from Latex. To install it on Mac OS:
#+begin_src bash :results none :tangle no
brew install --cask font-computer-modern
#+end_src
** Functions for modifying appearance for writing mode
#+begin_src elisp :results none
(define-minor-mode ak/writing-mode
  "A minor mode for distraction-free writing.

Enables variable-pitch font, olivetti mode, removes line numbers,
increases text scale, and disables line highlighting."
  :lighter " Writing"
  :group 'ak
  (if ak/writing-mode
      ;; Enable writing mode
      (progn
        (variable-pitch-mode 1)
        (olivetti-mode 1)
        (display-line-numbers-mode -1)
        (text-scale-increase 2)
        (setq-local global-hl-line-mode nil)
        (hl-line-mode -1)
        (remove-overlays (point-min) (point-max) 'face 'hl-line)
        (set-face-attribute 'variable-pitch nil :family "CMU Serif"))
    ;; Disable writing mode
    (olivetti-mode -1)
    (kill-local-variable 'global-hl-line-mode)
    (when global-hl-line-mode (hl-line-mode 1))
    (display-line-numbers-mode 1)
    (text-scale-increase -2)
    (variable-pitch-mode -1)))
#+end_src
** Some sample prose
This is prose, and /this/ is prose *too*!
** Keybinding for writing mode
#+begin_src elisp :results none
(global-set-key (kbd "C-x A w") #'ak/writing-mode)
#+end_src
** Keep tables and source blocks in fixed-pitch font
When ~variable-pitch-mode~ is active (e.g. via ~ak/writing-mode~), org tables and
source blocks should remain monospace. Setting these faces to inherit ~fixed-pitch~
ensures they stay monospace regardless of the default face.
#+begin_src elisp :results none
(set-face-attribute 'org-table nil :inherit 'fixed-pitch)
(set-face-attribute 'org-block nil :inherit 'fixed-pitch)
(set-face-attribute 'org-block-begin-line nil :inherit 'fixed-pitch)
(set-face-attribute 'org-block-end-line nil :inherit 'fixed-pitch)
(set-face-attribute 'org-code nil :inherit 'fixed-pitch)
(set-face-attribute 'org-verbatim nil :inherit 'fixed-pitch)
#+end_src

The same applies in ~markdown-mode~: code spans, code blocks, and tables should stay
monospace when ~variable-pitch-mode~ is active.
#+begin_src elisp :results none
(set-face-attribute 'markdown-code-face nil :inherit 'fixed-pitch)
(set-face-attribute 'markdown-pre-face nil :inherit 'fixed-pitch)
(set-face-attribute 'markdown-table-face nil :inherit 'fixed-pitch)
(set-face-attribute 'markdown-inline-code-face nil :inherit 'fixed-pitch)
#+end_src
